services:
  backend:
    image: "${DOCKER_IMAGE_BACKEND}:${TAG-latest}"
    build:
      context: ./backend
    restart: always
    env_file:
      - .env
    environment:
      DOMAIN: ${DOMAIN}
      FRONTEND_HOST: ${FRONTEND_HOST}
      ENVIRONMENT: ${ENVIRONMENT}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      SECRET_KEY: ${SECRET_KEY}
      FIRST_SUPERUSER: ${FIRST_SUPERUSER}
      FIRST_SUPERUSER_PASSWORD: ${FIRST_SUPERUSER_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      EMAILS_FROM_EMAIL: ${EMAILS_FROM_EMAIL}
      SQLITE_DB: ${SQLITE_DB}
      SENTRY_DSN: ${SENTRY_DSN}
    ports:
      - "8000:8000"
    volumes:
      - sqlite-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/health-check/"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.services.${STACK_NAME}-backend.loadbalancer.server.port=8000
      - traefik.http.routers.${STACK_NAME}-backend-http.rule=Host(`api.${DOMAIN}`)
      - traefik.http.routers.${STACK_NAME}-backend-http.entrypoints=http
      - traefik.http.routers.${STACK_NAME}-backend-http.middlewares=https-redirect
      - traefik.http.routers.${STACK_NAME}-backend-https.rule=Host(`api.${DOMAIN}`)
      - traefik.http.routers.${STACK_NAME}-backend-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME}-backend-https.tls=true
      - traefik.http.routers.${STACK_NAME}-backend-https.tls.certresolver=le

volumes:
  sqlite-data:

networks:
  traefik-public:
    external: true
